version: '3.3'

volumes:
  db_vol:
  static_value:
  media_value:
  redoc:

services:

  db:
    image: postgres:13
    volumes:
      - db_vol:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  backend:
      image: voltorrr/foodgram_backend
      restart: always
      volumes:
        - static_value:/app/static/
        - media_value:/app/media/
        - redoc:/app/api/docs/
      depends_on:
        - db
      env_file:
        - ./.env

  frontend:
    image: voltorrr/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx_local.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
    restart: always

